
skillMetadata:
  sections:
    - name: Production Server
      fields:
        - type: label
          label: Configure production server settings.
        - name: message_server_host
          type: text
          label: Message server hostname (or hostname:port)
          value: ""
          placeholder: ""
